// Generated by CoffeeScript 1.6.1
(function() {
  var Utils;

  Utils = (function() {

    function Utils() {}

    Utils.isKmart = function() {
      return localStorage.appId === "kmart";
    };

    return Utils;

  })();

  window.Utils = Utils;

}).call(this);
