// Generated by CoffeeScript 1.6.1

/*

Go back directive to bind to html elements 
for the back button
*/


(function() {
  'use strict';
  var directives;

  directives = angular.module('go-back.directives', []);

  directives.directive('goBack', function($compile, $location) {
    return {
      restrict: 'A',
      compile: function(element, attrs, transinclude) {
        return {
          pre: function(scope, element, attrs, controller) {},
          post: function(scope, element, attrs, controller) {
            return element.bind("click", function(e) {
              return window.history.back();
            });
          }
        };
      }
    };
  });

}).call(this);
