// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var directives;

  directives = angular.module('slider.directives', []);

  directives.directive('slider', function($compile, $location) {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {


          element.noUiSlider({
              range: [scope.minMax.min, scope.minMax.max],
              start: [scope.minMax.min, scope.minMax.max],
              step: .01,
              slide: function () {
                  var values;

                  values = $(this).val();
                  scope.minMax.min = values[0];
                  scope.minMax.max = values[1];
                  return $(".range").text("$" + values[0] + " - " + "$" + values[1]);
              }
          });

          var handles= element.find('div');

          if(handles.length === 2){
             scope.leftHandle= handles[0];
             scope.rightHandle= handles[1];
          }

           return element;
      }
    };
  });

}).call(this);


/*

range: [scope.minMax.min, scope.minMax.max],
    start: [scope.minMax.min, scope.minMax.max],
    step: .01,
    slide: function() {
    var values;

    values = $(this).val();
    scope.minMax.min = values[0];
    scope.minMax.max = values[1];
    return $(".range").text("$" + values[0] + " - " + "$" + values[1]);*/
