// Generated by CoffeeScript 1.6.1
(function() {

  angular.module('bannerService', ['ngResource']).factory('bannerService', function($resource, $q) {
    var bannerService;
    bannerService = (function() {

      function bannerService() {}

      bannerService.prototype.load = function() {
        var deferred, options, res, url;
        url = "https://cloudfish.herokuapp.com/banner";
        deferred = $q.defer();
        options = {
          query: {
            method: "GET",
            isArray: false
          }
        };
        res = $resource(url, {}, options);
        res.get(function(data) {
          return deferred.resolve(data);
        });
        return deferred.promise;
      };

      return bannerService;

    })();
    return window.bannerService = new bannerService();
  });

}).call(this);
